### PR TITLE
Scripting support

### PR DESCRIPTION
**Pull request by michaelmior**
Curious if any work has been done on this. I may start hacking on it myself. In terms of the JSON structure, I was thinking `{before,after}_bootstrap` keys in the JSON which would simply contain an array of strings which would be executed in a subshell. Thoughts?

### CODE REVIEW

**Comment by michaelmior** [comment]
Hacked something together quickly that's working well for me. Haven't really thought about how to properly test it though. What's the quickest way to get the test suite running. Just running `rake` gives me a bunch of errors.

**Comment by ukd1** [comment]
@michaelmior the build failed for this...plus...sorry it's been so long since I replied.

**Comment by michaelmior** [comment]
Sorry, didn't notice the build failed. Unfortunately, the build is also failing on master for me now. https://travis-ci.org/michaelmior/heroku.json/jobs/14636867

**Comment by michaelmior** [comment]
Is there any particular reason `Gemfile.lock` is in `.gitignore`? I suspect there's a decent chance the issue is related to incompatibility with new versions of gems.

**Comment by michaelmior** [comment]
Actually, looking at the history on Travis CI, it seems nearly every build has failed in the entire repository history. Any thoughts on where to start fixing this?

**Pull request closed without merging**
