### PR TITLE
New variables for blacklist

### PR DESCRIPTION
**Pull request by michaelmior**
Here's a few variables which seem common enough to be worth of the blacklist.

These are provided by add-ons and are app-specific, so are useless in the JSON.

```
NEW_RELIC_ID
NEW_RELIC_LOG
NEW_RELIC_LICENSE_KEY
SEARCHBOX_URL
NEW_RELIC_APP_NAME
SENTRY_DSN
```

These are perhaps arguable, but it seems they still shouldn't be there by default.

```
LIBRARY_PATH
LANG
PYTHONPATH
LD_LIBRARY_PATH
PYTHONUNBUFFERED
PYTHONHASHSEED
PATH
PYTHONHOME
```

Thanks!

### CODE REVIEW

**Comment by ukd1** [comment]
@michaelmior could you get this build to pass?

**Comment by michaelmior** [comment]
Sure, I'll check this out tomorrow. Didn't notice the build had failed.

**Comment by michaelmior** [comment]
Build is failing for me on master as well. I'm not a Rubyist. Could you check it out?

**Comment by ukd1** [comment]
@michaelmior sure

**Comment by ukd1** [comment]
@michaelmior should be better now, merge in the fix I just pushed :+1:

**Comment by michaelmior** [comment]
Seems to still be failing, but with a different error.

**Comment by michaelmior** [comment]
Closing this since this project is no longer active and seems obsoleted by [app.json](https://github.com/app-json/app.json).

**Comment by zeke** [comment]
`app.json` drew inspiration from `heroku.json`

:)

**Comment by ukd1** [comment]
@zeke <3 - just updated the readme to reflect this projects status (aka replaced by app.json)

**Pull request closed without merging**
